### ISSUE TITLE
PlaceBooking.Database.Booker should be in Simplified namespace

### ISSUE THREAD

**Issue by linkdata** [StarcounterSamples/Simplified#10]
The database class PlaceBooking.Database.Booker should be in Simplified namespace.
https://github.com/StarcounterSamples/Simplified/blob/master/Ring6/Booker.cs
See https://github.com/Starcounter/Replicator/issues/21

**Comment by warpech** [comment]
Thanks for reporting. @andwah could you do this?

**Comment by andwah** [comment]
@warpech Sure.

**Comment by andwah** [comment]
Fixed.

**Comment by warpech** [comment]
Thanks
