### ISSUE TITLE
SessionIdString is deprecated

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Simplified#12]
I get the following warnings at compile time (three times in `SystemUser.Static.cs`):

```
CS0618: 'Session.SessionIdString' is obsolete: 'Please use ToAsciiString() instead.'
CS0618: 'Session.SessionIdString' is obsolete: 'Please use ToAsciiString() instead.'
CS0618: 'Session.SessionIdString' is obsolete: 'Please use ToAsciiString() instead.'
```

cc @miyconst

**Comment by miyconst** [comment]
This is a change in Starcounter made by @alemoi, I can fix Simplified to use the latest version.

**Comment by alemoi** [comment]
Yes, that is true. Next time when having breaking changes i will go through all apps we supply, I think @warpech even created an issue regarding such list somewhere. I would also suggest making Simplified treat warnings as errors on all projects.
