### ISSUE TITLE
Organization.ContactPersons exception

### ISSUE THREAD

**Issue by diliger** [StarcounterSamples/Simplified#13]
I was unable to use Organization.ContactPersons because of an exception:

> Failed to process query: SELECT c.Person FROM OrganizationPerson c WHERE c.Organization = ?: Unknown class OrganizationPerson. Unknown property Person of class OrganizationPerson. Unknown property Organization of class OrganizationPerson.

I read the code of Organization class here https://github.com/StarcounterSamples/Simplified/blob/master/Ring2/Organization.cs

and see there is a query without full name of OrganizationPerson class, so that's probably the issue.

**Comment by miyconst** [comment]
Good catch. I will fix that.

**Comment by miyconst** [comment]
Fixed.
