### ISSUE TITLE
Build fail: dependency to SO libraries not resolved

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterSamples/Simplified#6]
I have a locally built Starcounter, based on standard Level1.sln.

When I clone `Simplified` and build it, the mapper (`Simplified.Mapper`) fail to build. I diagnosed it, and it's because it depends on SO concepts ring libraries in hinted paths like these:

> <HintPath>$(StarcounterBin)\EditionLibraries\SocietyObjects.Concepts.Ring2.dll</HintPath>

I don't have any such libraries on my machine it seem. Is there some manual step I need to do to get `Simplified` to build successfully?

/cc @miyconst @chrhol @alemoi

**Comment by chrhol** [comment]
I assume that you build Starcounter locally and not using an installer? Then you need to either build SO from StarcounterSamples or exclude `Simplified.Mapper`. 

If you are using an downloaded installer and the  SO libraries are missing then something is wrong, these files should be included.

**Comment by chrhol** [comment]
> I have a locally built Starcounter, based on standard Level1.sln.

Didn't read the first line obviously :)

**Comment by per-samuelsson** [comment]
> I assume that you build Starcounter locally and not using an installer? Then you need to either build SO from StarcounterSamples or exclude Simplified.Mapper.

Yes, I do, as I wrote:

> I have a locally built Starcounter, based on standard Level1.sln.

:sunglasses:

**Comment by per-samuelsson** [comment]
>  Then you need to either build SO from StarcounterSamples or exclude Simplified.Mapper.

OK. Maybe we should include that in the build instructions on in the ReadMe?

Thanks for the help.

**Comment by chrhol** [comment]
I*m not sure that `Simplified.Mapper` should be a part of the standard `Simplified` solution. I think we need to discuss how to practically handle this.

**Comment by per-samuelsson** [comment]
> I*m not sure that Simplified.Mapper should be a part of the standard Simplified solution. I think we need to discuss how to practically handle this.

That will have to be in a separate issue, as I'm closing this one now (my question was answered). :smile:
