### ISSUE TITLE
[Question] Process of extending the library?

### ISSUE THREAD

**Issue by jwillmer** [StarcounterSamples/Simplified#7]
Is it desired to extend the library? For example I would like to use the library to be able to use the demo apps besides my own but I need a weight field in the person model.

Shall I fork it and extend it or does it make sense to incoperate it in the existing library?

**Comment by per-samuelsson** [comment]
@jwillmer 

From what I understand by the [contribution guidelines](https://github.com/StarcounterSamples/Simplified#how-to-contribute) the idea is to bring stuff in eventually. But let's see what the main guys have to say about it; I'm interested too. :curly_loop:

**Comment by miyconst** [comment]
Yes, you can extend the model with a Pull Request.

**Comment by jwillmer** [comment]
Pull Request: #8
