### ISSUE TITLE
How to switch the Simpliefied.dll with a new version?

### ISSUE THREAD

**Issue by jwillmer** [StarcounterSamples/Simplified#9]
What do I have to do if the Simplified library is newer than the version that comes with Starcounter and I want to replace it?

**Comment by miyconst** [comment]
You have to open Simplified solution in VisualStudio and rebuild it. Starcounter server has to be restarted to take the changes.

**Comment by warpech** [comment]
Actually README.md has this information. Should this be further clarified?

**Comment by jwillmer** [comment]
Worked for me. Just havent seen it ;)
